inherit_gem:
    rubocop-shopify: rubocop.yml

require: 
  - rubocop-rspec

Style/MethodCallWithArgsParentheses: 
  Enabled: false
Style/SymbolArray:
  Enabled: true
  EnforcedStyle: percent

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
